---
theme: PLACEHOLDER
style: PLACEHOLDER
catppuccin_window_tabs_enabled: PLACEHOLDER
catppuccin_pill_theme_enabled: PLACEHOLDER
catppuccin_powerline_theme_enabled: PLACEHOLDER
catppuccin_powerline_icons_theme_enabled: PLACEHOLDER
catppuccin_no_patched_fonts_theme_enabled: PLACEHOLDER
catppuccin_l_left_separator: PLACEHOLDER
catppuccin_l_right_separator: PLACEHOLDER
catppuccin_r_left_separator: PLACEHOLDER
catppuccin_r_right_separator: PLACEHOLDER
catppuccin_user: PLACEHOLDER
catppuccin_host: PLACEHOLDER
catppuccin_date_time: PLACEHOLDER
catppuccin_directory_icon: PLACEHOLDER
catppuccin_window_icon: PLACEHOLDER
catppuccin_session_icon: PLACEHOLDER
catppuccin_user_icon: PLACEHOLDER
catppuccin_host_icon: PLACEHOLDER
catppuccin_datetime_icon: PLACEHOLDER
