---
theme: violet
style: nobold,nounderscore,noitalics
catppuccin_window_tabs_enabled: off
catppuccin_pill_theme_enabled: off
catppuccin_powerline_theme_enabled: off
catppuccin_powerline_icons_theme_enabled: off
catppuccin_no_patched_fonts_theme_enabled: off
catppuccin_l_left_separator: ""
catppuccin_l_right_separator: ""
catppuccin_r_left_separator: ""
catppuccin_r_right_separator: ""
catppuccin_user: off
catppuccin_host: off
catppuccin_date_time: off
catppuccin_directory_icon: ""
catppuccin_window_icon: ""
catppuccin_session_icon: " "
catppuccin_user_icon: "v%V %a %Y-%m-%d %H:%M:%S"
catppuccin_host_icon: ""
catppuccin_datetime_icon: ""
